export const SECTION_TITLES: [string, string][] = [
  ['/tools', 'Forge Tools'],
  // Universal Albion crafting tools (user-owned prices, no live market).
  ['/games/albion/item-index', 'Albion - Item Index'],
  ['/games/albion/item/', 'Albion - Item'],
  ['/games/albion/favourites', 'Albion - Favourite Items'],
  ['/games/albion/gold', 'Albion - Gold Price'],
  ['/games/albion', 'Albion'],
  ['/games/ffxi/skillchain-calc', 'FFXI - Skillchain Calc'],
  ['/games/ffxi/vana-timers', 'FFXI - Vana Timers'],
  ['/games/ffxi/map', 'FFXI - Interactive Map'],
  ['/games/ffxi/quest-tracker', 'FFXI - Quest Tracker'],
  ['/games/ffxi/spell-tracker', 'FFXI - Spell Tracker'],
  ['/games/ffxi/key-item-tracker', 'FFXI - Key Item Tracker'],
  ['/games/ffxi/lockouts', 'FFXI - Lockout Tracker'],
  ['/games/ffxi/clamming-tracker', 'FFXI - Clamming Tracker'],
  ['/games/ffxi/faction-conquest', 'FFXI - Faction Conquest'],
  ['/games/ffxi/friend-viewer', 'FFXI - Friend Viewer'],
  ['/games/ffxi', 'FFXI'],
  ['/games', 'Forge Games'],
  ['/', 'FORGEHAVEN'],
]
