export const STORAGE_KEYS = {
  favourites:              'forgetools_favourites',
  cityFavourites:          'forgetools_city_favourites',
  collapsedSections:       'forgetools_collapsed_sections',
  gamesCollapsedSections:  'forgegames_collapsed_sections',
  tempUnit:                'forgetools_temp_unit',
  ipCache:                 'forge_ip_v2',
  ffxiSpellTracker:        'forgegames_ffxi_spelltracker_v1',
  // Value keeps the old teleportcost slug so existing browsers keep their data.
  ffxiFactionConquest:     'forgegames_ffxi_teleportcost_v1',
  ffxiClamming:            'forgegames_ffxi_clamming_v1',
  ffxiFriendViewer:        'forgegames_ffxi_friendviewer_v1',
  ffxiQuestTracker:        'forgegames_ffxi_questtracker_v1',
  ffxiKeyItems:            'forgegames_ffxi_keyitems_v1',
  ffxiKeyItemsNoSync:      'forgegames_ffxi_keyitems_nosync_v1',
  albionItemFavourites:    'forgegames_albion_item_favourites_v1',
  albionUserPrices:        'forgegames_albion_user_prices_v1',
  albionUserCraftSettings: 'forgegames_albion_user_craft_settings_v1',
  ffxiSelectedChar:        'forgegames_ffxi_selectedchar_v1',
  ffxiSpellNoSync:         'forgegames_ffxi_spelltracker_nosync_v1',
  ffxiSpellMirrorChar:     'forgegames_ffxi_spelltracker_mirrorchar_v1',
  ffxiKeyItemsMirrorChar:  'forgegames_ffxi_keyitems_mirrorchar_v1',
  ffxiVanaTimers:          'forgegames_ffxi_vanatimers_v1',
  gameAlarms:              'forgegames_alarms_v1',
  ffxiLockouts:            'forgegames_ffxi_lockouts_v1',
  ffxiMap:                 'forgegames_ffxi_map_v1',
} as const
