export const STORAGE_KEYS = {
  favourites:              'forgetools_favourites',
  cityFavourites:          'forgetools_city_favourites',
  collapsedSections:       'forgetools_collapsed_sections',
  gamesCollapsedSections:  'forgegames_collapsed_sections',
  tempUnit:                'forgetools_temp_unit',
  ipCache:                 'forge_ip_v2',
  ffxiSpellTracker:        'forgegames_ffxi_spelltracker_v1',
  ffxiTeleportCost:        'forgegames_ffxi_teleportcost_v1',
  ffxiClamming:            'forgegames_ffxi_clamming_v1',
  ffxiFriendViewer:        'forgegames_ffxi_friendviewer_v1',
  ffxiQuestTracker:        'forgegames_ffxi_questtracker_v1',
  ffxiKeyItems:            'forgegames_ffxi_keyitems_v1',
  ffxiKeyItemsNoSync:      'forgegames_ffxi_keyitems_nosync_v1',
  albionItemFavourites:    'forgegames_albion_item_favourites_v1',
  albionMMCollapsed:       'forgegames_albion_mm_collapsed_v1',
  ffxiSelectedChar:        'forgegames_ffxi_selectedchar_v1',
  ffxiSpellNoSync:         'forgegames_ffxi_spelltracker_nosync_v1',
} as const
